import type { Agent, Post, Conversation, Match, Message } from "./types"

// Mock current user
export const currentUser: Agent = {
  id: "user-1",
  name: "张明科技",
  email: "zhang@example.com",
  avatar: undefined,
  agentType: "company",
  industry: ["人工智能", "软件开发"],
  capabilities: ["机器学习", "自然语言处理", "数据分析"],
  description: "专注于AI解决方案的科技公司，提供定制化的智能服务",
  location: "上海",
  verified: true,
  createdAt: new Date("2024-01-15"),
}

// Mock agents
export const mockAgents: Agent[] = [
  currentUser,
  {
    id: "agent-2",
    name: "李华智能助手",
    email: "li@example.com",
    agentType: "ai_assistant",
    industry: ["客户服务", "电商"],
    capabilities: ["智能客服", "订单处理", "数据分析"],
    description: "专业的AI客服助手，支持多语言、24小时在线服务",
    location: "北京",
    verified: true,
    createdAt: new Date("2024-02-20"),
  },
  {
    id: "agent-3",
    name: "王强咨询",
    email: "wang@example.com",
    agentType: "individual",
    industry: ["金融科技", "区块链"],
    capabilities: ["智能合约", "DeFi开发", "安全审计"],
    description: "资深区块链开发者，专注于DeFi和智能合约安全",
    location: "深圳",
    verified: true,
    createdAt: new Date("2024-03-10"),
  },
  {
    id: "agent-4",
    name: "创新数据科技",
    email: "innovation@example.com",
    agentType: "company",
    industry: ["大数据", "云计算"],
    capabilities: ["数据仓库", "实时分析", "数据可视化"],
    description: "提供企业级大数据解决方案和云端分析服务",
    location: "杭州",
    verified: false,
    createdAt: new Date("2024-04-05"),
  },
  {
    id: "agent-5",
    name: "智慧医疗AI",
    email: "health@example.com",
    agentType: "company",
    industry: ["医疗健康", "人工智能"],
    capabilities: ["医学影像分析", "诊断辅助", "健康管理"],
    description: "运用AI技术提升医疗诊断效率和准确性",
    location: "广州",
    verified: true,
    createdAt: new Date("2024-04-15"),
  },
]

// Mock posts
export const mockPosts: Post[] = [
  {
    id: "post-1",
    authorId: "user-1",
    author: currentUser,
    type: "supply",
    title: "提供NLP模型定制开发服务",
    description: "我们团队擅长自然语言处理，可以根据您的业务需求定制训练模型，包括文本分类、情感分析、实体识别等。",
    category: "技术服务",
    tags: ["NLP", "机器学习", "模型训练"],
    budget: { min: 50000, max: 200000, currency: "CNY" },
    timeline: "2-4周",
    status: "active",
    createdAt: new Date("2024-05-01"),
    updatedAt: new Date("2024-05-01"),
  },
  {
    id: "post-2",
    authorId: "agent-2",
    author: mockAgents[1],
    type: "demand",
    title: "寻求电商平台智能客服集成",
    description: "需要将AI客服系统集成到现有电商平台，要求支持多轮对话、商品推荐和订单查询功能。",
    category: "技术合作",
    tags: ["客服系统", "电商", "API集成"],
    budget: { min: 30000, max: 80000, currency: "CNY" },
    timeline: "1个月内",
    requirements: ["支持微信/网页多端", "日均10万+对话量", "99.9%可用性"],
    status: "active",
    createdAt: new Date("2024-05-05"),
    updatedAt: new Date("2024-05-05"),
  },
  {
    id: "post-3",
    authorId: "agent-3",
    author: mockAgents[2],
    type: "supply",
    title: "智能合约安全审计服务",
    description: "提供专业的智能合约安全审计，包括漏洞检测、代码审查和安全建议报告。",
    category: "安全服务",
    tags: ["智能合约", "安全审计", "区块链"],
    budget: { min: 20000, max: 100000, currency: "CNY" },
    timeline: "1-2周",
    status: "active",
    createdAt: new Date("2024-05-08"),
    updatedAt: new Date("2024-05-08"),
  },
  {
    id: "post-4",
    authorId: "agent-4",
    author: mockAgents[3],
    type: "demand",
    title: "需要AI数据标注合作伙伴",
    description: "我们正在开发一个大型语言模型，需要高质量的中文数据标注服务，包括问答对、对话数据等。",
    category: "数据服务",
    tags: ["数据标注", "LLM", "中文数据"],
    budget: { min: 100000, max: 500000, currency: "CNY" },
    timeline: "长期合作",
    requirements: ["专业标注团队", "质量控制流程", "数据安全保障"],
    status: "active",
    createdAt: new Date("2024-05-10"),
    updatedAt: new Date("2024-05-10"),
  },
  {
    id: "post-5",
    authorId: "agent-5",
    author: mockAgents[4],
    type: "supply",
    title: "医学影像AI分析API",
    description: "提供医学影像分析API服务，支持CT、MRI、X光等影像的智能分析和辅助诊断。",
    category: "医疗AI",
    tags: ["医学影像", "辅助诊断", "API"],
    budget: { min: 10000, max: 50000, currency: "CNY" },
    timeline: "按调用量计费",
    status: "active",
    createdAt: new Date("2024-05-12"),
    updatedAt: new Date("2024-05-12"),
  },
]

// Mock matches
export const mockMatches: Match[] = [
  {
    id: "match-1",
    postId: "post-1",
    post: mockPosts[0],
    matchedAgentId: "agent-2",
    matchedAgent: mockAgents[1],
    score: 92,
    reasons: [
      "需求方正在寻找NLP相关技术服务",
      "预算范围匹配",
      "技术能力契合度高",
    ],
    status: "suggested",
    createdAt: new Date("2024-05-15"),
  },
  {
    id: "match-2",
    postId: "post-1",
    post: mockPosts[0],
    matchedAgentId: "agent-4",
    matchedAgent: mockAgents[3],
    score: 85,
    reasons: [
      "正在进行LLM开发项目",
      "对NLP模型有明确需求",
      "长期合作潜力大",
    ],
    status: "contacted",
    createdAt: new Date("2024-05-14"),
  },
  {
    id: "match-3",
    postId: "post-2",
    post: mockPosts[1],
    matchedAgentId: "user-1",
    matchedAgent: currentUser,
    score: 88,
    reasons: [
      "您具备NLP和对话系统开发能力",
      "曾完成类似电商项目",
      "技术栈高度匹配",
    ],
    status: "suggested",
    createdAt: new Date("2024-05-16"),
  },
]

// Mock conversations
export const mockConversations: Conversation[] = [
  {
    id: "conv-1",
    participants: [currentUser, mockAgents[1]],
    lastMessage: {
      id: "msg-1",
      conversationId: "conv-1",
      senderId: "agent-2",
      content: "您好，我们对您的NLP服务很感兴趣，方便详细聊聊吗？",
      createdAt: new Date("2024-05-15T10:30:00"),
      read: false,
    },
    relatedPostId: "post-1",
    createdAt: new Date("2024-05-15"),
    updatedAt: new Date("2024-05-15T10:30:00"),
  },
  {
    id: "conv-2",
    participants: [currentUser, mockAgents[3]],
    lastMessage: {
      id: "msg-2",
      conversationId: "conv-2",
      senderId: "user-1",
      content: "好的，我明天发送详细的技术方案给您",
      createdAt: new Date("2024-05-14T16:45:00"),
      read: true,
    },
    relatedPostId: "post-4",
    createdAt: new Date("2024-05-14"),
    updatedAt: new Date("2024-05-14T16:45:00"),
  },
]

// Mock messages for a conversation
export const mockMessages: Message[] = [
  {
    id: "msg-1-1",
    conversationId: "conv-1",
    senderId: "agent-2",
    content: "您好！我是李华智能助手的负责人。",
    createdAt: new Date("2024-05-15T10:00:00"),
    read: true,
  },
  {
    id: "msg-1-2",
    conversationId: "conv-1",
    senderId: "agent-2",
    content: "看到您发布的NLP模型定制开发服务，我们目前正在升级客服系统，需要更强大的意图识别能力。",
    createdAt: new Date("2024-05-15T10:02:00"),
    read: true,
  },
  {
    id: "msg-1-3",
    conversationId: "conv-1",
    senderId: "user-1",
    content: "您好！很高兴收到您的消息。我们在意图识别方面有丰富经验，可以针对客服场景进行优化。",
    createdAt: new Date("2024-05-15T10:15:00"),
    read: true,
  },
  {
    id: "msg-1-4",
    conversationId: "conv-1",
    senderId: "user-1",
    content: "您方便介绍一下目前的技术栈和具体需求吗？",
    createdAt: new Date("2024-05-15T10:16:00"),
    read: true,
  },
  {
    id: "msg-1-5",
    conversationId: "conv-1",
    senderId: "agent-2",
    content: "您好，我们对您的NLP服务很感兴趣，方便详细聊聊吗？",
    createdAt: new Date("2024-05-15T10:30:00"),
    read: false,
  },
]

// Industry options
export const industryOptions = [
  "人工智能",
  "软件开发",
  "金融科技",
  "医疗健康",
  "电商零售",
  "教育培训",
  "游戏娱乐",
  "物流运输",
  "制造业",
  "区块链",
  "大数据",
  "云计算",
  "物联网",
  "网络安全",
  "其他",
]

// Capability options
export const capabilityOptions = [
  "机器学习",
  "深度学习",
  "自然语言处理",
  "计算机视觉",
  "语音识别",
  "推荐系统",
  "数据分析",
  "数据标注",
  "API开发",
  "系统集成",
  "安全审计",
  "智能客服",
  "流程自动化",
  "咨询服务",
  "其他",
]

// Post categories
export const postCategories = [
  "技术服务",
  "技术合作",
  "数据服务",
  "安全服务",
  "医疗AI",
  "金融AI",
  "教育AI",
  "咨询服务",
  "外包开发",
  "其他",
]
